# Generated by Django 4.1.5 on 2023-02-14 10:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_usertype_users_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
